name: nlp_rag_fin
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=2.2.6
  - pandas=2.3.3
  - scipy=1.15.3
  - scikit-learn=1.7.2
  - pytorch=2.9.1
  - cpuonly  # Change to 'pytorch-cuda=12.1' if you have an NVIDIA GPU
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - psutil
  - requests=2.32.5
  - pyyaml=6.0.3
  - sqlite
  - tqdm
  - colorama
  - pip:
      - langchain==0.3.27
      - langchain-community==0.3.31
      - langchain-core==0.3.80
      - langchain-google-genai==2.0.10
      - langchain-ollama==0.2.2
      - llama-index==0.14.8
      - llama-index-core==0.14.8
      - llama-parse==0.6.54
      - llama-index-embeddings-huggingface==0.6.1
      - llama-index-llms-gemini==0.6.1
      - google-generativeai==0.8.5
      - openai==2.8.1
      - ollama==0.6.1
      - fastapi==0.128.0
      - uvicorn==0.40.0
      - gradio==6.3.0
      - transformers==4.57.3
      - sentence-transformers==5.1.2
      - pydantic==2.12.4
      - tiktoken==0.12.0
      - nltk==3.9.2
      - pypdf==6.4.0
      - python-dotenv==1.2.1