name: nlp_rag_ollama
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.19=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.9.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=hc70643c_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - parso=0.8.5=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py311h3485c13_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - brotli==1.2.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - dataclasses-json==0.6.7
      - deprecated==1.3.1
      - dirtyjson==1.0.8
      - fastapi==0.128.0
      - ffmpy==1.0.0
      - filelock==3.20.3
      - filetype==1.2.0
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - gradio==6.3.0
      - gradio-client==2.0.3
      - greenlet==3.3.0
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.14
      - langchain-core==0.3.30
      - langchain-ollama==0.2.2
      - langchain-text-splitters==0.3.5
      - langsmith==0.2.11
      - llama-index-core==0.12.12
      - llama-index-embeddings-ollama==0.5.0
      - llama-index-llms-ollama==0.5.0
      - llama-index-postprocessor-sbert-rerank==0.5.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - mdurl==0.1.2
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - nltk==3.9.2
      - numpy==1.26.4
      - ollama==0.6.1
      - orjson==3.11.5
      - packaging==24.2
      - pandas==2.3.3
      - pillow==12.1.0
      - propcache==0.4.1
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - safehttpx==0.1.7
      - semantic-version==2.10.0
      - sentence-transformers==3.3.1
      - shellingham==1.5.4
      - sqlalchemy==2.0.45
      - starlette==0.50.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - torch==2.5.1
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-inspect==0.9.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - wrapt==2.0.1
      - yarl==1.22.0
